// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	decimal "github.com/shopspring/decimal"
)

type Product struct {
	ID          int64           `json:"id"`
	CreatedAt   time.Time       `json:"created_at"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Price       decimal.Decimal `json:"price"`
}
